name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" > .env
          npx vercel --prod

      - name: Add Vercel deployment URL
        run: |
          echo "Deployment URL: https://${{ github.event.repository.name }}.vercel.app" >> $GITHUB_STEP_SUMMARY 